version: 0.2

phases:
    pre_build:
        commands:
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - docker build -t todo-business:latest .
            - docker tag todo-business:latest 314749681433.dkr.ecr.us-west-2.amazonaws.com/todo-business:latest
            - docker push 314749681433.dkr.ecr.us-west-2.amazonaws.com/todo-business:latest
    post_build:
        commands:
            - aws ecs update-service --service "arn:aws:ecs:us-west-2:314749681433:service/todo-api" --cluster "arn:aws:ecs:us-west-2:314749681433:cluster/todo-api" --force-new-deployment